# Render.yaml configuration for deploying the backend
services:
  - type: web
    name: indian-investment-advisor-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
